const path=require('path')
require('dotenv').config({path:path.resolve(__dirname,'./.env')})
const express=require('express')
const app= express()
const dbconnection =require('./db')
const taskRoutes=require('./routes/tasks')
const userRoutes=require('./routes/users')
dbconnection()
const cors=require('cors')
app.use(express.json({limit:"30mb",extended:true}))
app.use(express.urlencoded({limit:"30mb",extended:true}))
app.use(cors())
app.use('/tasks',taskRoutes)
app.use('/user',userRoutes)

app.listen(process.env.PORT,()=>{console.log(`App is listening on ${process.env.PORT}`)})